-- Migration 019: management listening channel — «Поговорить с руководством»
--
-- This surface is wave-based, not period-based. It has no period_id, score,
-- weight, coefficient, rating, rank or count column, and no foreign key into
-- evaluations, evaluation_scores, score_corrections or period_results.
-- Integer columns below are identifiers only. Responders and every named
-- counterpart reference performance_db.users(id), exactly as peer recognition.
--
-- Wave 1 opens when this migration is first applied and closes at the end of
-- 2026-09-10 in Asia/Ashgabat. Re-running the migration never moves either
-- timestamp. Response and counterpart tables start empty.
--
-- User-entered free text is impossible: every response value is a constrained
-- key and every topic label is fixed here by the approved business contract.
--
-- Safety: additive, idempotent, single transaction.

BEGIN;

CREATE TABLE IF NOT EXISTS performance_db.management_talk_waves (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wave_key   text        NOT NULL UNIQUE,
    opens_at   timestamptz NOT NULL,
    closes_at  timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_management_talk_wave_window CHECK (closes_at > opens_at)
);

CREATE TABLE IF NOT EXISTS performance_db.management_talk_topics (
    topic_key text PRIMARY KEY,
    label     text NOT NULL UNIQUE,
    CONSTRAINT chk_management_talk_topic_key
        CHECK (topic_key ~ '^t(0[1-9]|1[0-2])_[a-z_]+$')
);

CREATE TABLE IF NOT EXISTS performance_db.management_talk_responses (
    wave_id             integer     NOT NULL
        REFERENCES performance_db.management_talk_waves(id),
    responder_id        integer     NOT NULL
        REFERENCES performance_db.users(id),
    answer_key          text        NOT NULL,
    topic_key           text        NULL
        REFERENCES performance_db.management_talk_topics(topic_key),
    counterpart_mode    text        NOT NULL DEFAULT 'none',
    urgency_key         text        NULL,
    group_readiness_key text        NULL,
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (wave_id, responder_id),
    CONSTRAINT chk_management_talk_answer_key CHECK (
        answer_key IN ('all_good', 'topic_only', 'conversation')
    ),
    CONSTRAINT chk_management_talk_counterpart_mode CHECK (
        counterpart_mode IN ('none', 'people', 'help_choose', 'all_leadership')
    ),
    CONSTRAINT chk_management_talk_urgency_key CHECK (
        urgency_key IS NULL
        OR urgency_key IN ('this_cycle', 'soon')
    ),
    CONSTRAINT chk_management_talk_group_readiness_key CHECK (
        group_readiness_key IS NULL
        OR group_readiness_key IN ('yes', 'individual_only')
    ),
    CONSTRAINT chk_management_talk_answer_shape CHECK (
        (
            answer_key = 'all_good'
            AND topic_key IS NULL
            AND counterpart_mode = 'none'
            AND urgency_key IS NULL
            AND group_readiness_key IS NULL
        )
        OR (
            answer_key = 'topic_only'
            AND topic_key IS NOT NULL
            AND counterpart_mode = 'none'
            AND urgency_key IS NULL
            AND group_readiness_key IS NULL
        )
        OR (
            answer_key = 'conversation'
            AND topic_key IS NOT NULL
            AND counterpart_mode IN ('people', 'help_choose', 'all_leadership')
            AND urgency_key IS NOT NULL
            AND group_readiness_key IS NOT NULL
        )
    )
);

CREATE TABLE IF NOT EXISTS performance_db.management_talk_counterparts (
    wave_id       integer NOT NULL,
    responder_id  integer NOT NULL,
    counterpart_id integer NOT NULL
        REFERENCES performance_db.users(id),
    PRIMARY KEY (wave_id, responder_id, counterpart_id),
    CONSTRAINT fk_management_talk_counterpart_response
        FOREIGN KEY (wave_id, responder_id)
        REFERENCES performance_db.management_talk_responses(wave_id, responder_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_management_talk_responses_updated
    ON performance_db.management_talk_responses (wave_id, updated_at DESC);

INSERT INTO performance_db.management_talk_topics (topic_key, label) VALUES
    ('t01_context', 'Хочу понять позицию руководства по ситуации или решению'),
    ('t02_workload', 'Нагрузка и объём работы'),
    ('t03_resources', 'Ресурсы или организация работы на проекте'),
    ('t04_role', 'Моя роль, ответственность или рабочие приоритеты'),
    ('t05_career', 'Карьерный рост и развитие'),
    ('t06_learning', 'Обучение и развитие компетенций'),
    ('t07_pay', 'Оплата или признание моего вклада'),
    ('t08_idea', 'Есть идея или предложение по улучшению работы'),
    ('t09_team', 'Отношения в команде, конфликт или токсичная атмосфера'),
    ('t10_manager', 'Действия моего непосредственного руководителя'),
    ('t11_unfair', 'Считаю ситуацию или решение несправедливым'),
    ('t12_personal', 'Есть личный вопрос, который хочу обсудить напрямую')
ON CONFLICT (topic_key) DO NOTHING;

INSERT INTO performance_db.management_talk_waves (wave_key, opens_at, closes_at)
VALUES (
    'talk-2026-wave-1',
    clock_timestamp(),
    TIMESTAMPTZ '2026-09-10 23:59:59.999999+05:00'
)
ON CONFLICT (wave_key) DO NOTHING;

COMMENT ON TABLE performance_db.management_talk_responses IS
    'Structured management-listening answers, one per wave and responder. Not an evaluation: no period_id and no score-like column or campaign-table foreign key.';
COMMENT ON COLUMN performance_db.management_talk_responses.responder_id IS
    'Token actor; integer identifier referencing users(id), never accepted from the request body.';
COMMENT ON TABLE performance_db.management_talk_counterparts IS
    'Named conversation counterparts. Every counterpart is an integer users(id) foreign key; special choices live in counterpart_mode and are mutually exclusive with these rows.';

COMMIT;
